name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to the GitHub Docker registry
    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . -t ghcr.io/${{ github.repository }}/myNode-docker-image:latest

    # Push the Docker image to GitHub Packages
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/myNode-docker-image:latest
