name: Maven Package Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      # Set up GitHub Packages Authentication for Maven
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Deploy the Maven package to GitHub Packages
      - name: Deploy package to GitHub Packages
        run: mvn deploy

      # Download and test the package from GitHub Packages
      - name: Download package from GitHub Packages
        run: mvn dependency:get -Dartifact=sunilsinghc11:mvn-gcr-local:0.0.1
