name: Build and Deploy Node.js Application

on:
  push:
    branches:
      - main  # Adjust as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build # Adjust if you have a different build command

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }} # Use GitHub token for authentication
